import type { COUNTRY_CODES } from '../codes';

const ES = {
  ABW: 'Aruba',
  AFG: 'Afganistán',
  AGO: 'Angola',
  AIA: 'Anguila',
  ALA: 'Åland',
  ALB: 'Albania',
  AND: 'Andorra',
  ARE: 'Emiratos Árabes Unidos',
  ARG: 'Argentina',
  ARM: 'Armenia',
  ASM: 'Samoa Americana',
  ATA: 'Antártida',
  ATF: 'Tierras Australes y Antárticas Francesas',
  ATG: 'Antigua y Barbuda',
  AUS: 'Australia',
  AUT: 'Austria',
  AZE: 'Azerbaiyán',
  BDI: 'Burundi',
  BEL: 'Bélgica',
  BEN: 'Benín',
  BES: 'Bonaire, San Eustaquio y Saba',
  BFA: 'Burkina Faso',
  BGD: 'Bangladés',
  BGR: 'Bulgaria',
  BHR: 'Baréin',
  BHS: 'Bahamas',
  BIH: 'Bosnia y Herzegovina',
  BLM: 'San Bartolomé',
  BLR: 'Bielorrusia',
  BLZ: 'Belice',
  BMU: 'Bermudas',
  BOL: 'Bolivia',
  BRA: 'Brasil',
  BRB: 'Barbados',
  BRN: 'Brunéi',
  BTN: 'Bután',
  BVT: 'Isla Bouvet',
  BWA: 'Botsuana',
  CAF: 'República Centroafricana',
  CAN: 'Canadá',
  CCK: 'Islas Cocos',
  CHE: 'Suiza',
  CHL: 'Chile',
  CHN: 'China',
  CIV: 'Costa de Marfil',
  CMR: 'Camerún',
  COD: 'República Democrática del Congo',
  COG: 'República del Congo',
  COK: 'Islas Cook',
  COL: 'Colombia',
  COM: 'Comoras',
  CPV: 'Cabo Verde',
  CRI: 'Costa Rica',
  CUB: 'Cuba',
  CUW: 'Curazao',
  CXR: 'Isla de Navidad',
  CYM: 'Islas Caimán',
  CYP: 'Chipre',
  CZE: 'República Checa',
  DEU: 'Alemania',
  DJI: 'Yibuti',
  DMA: 'Dominica',
  DNK: 'Dinamarca',
  DOM: 'República Dominicana',
  DZA: 'Argelia',
  ECU: 'Ecuador',
  EGY: 'Egipto',
  ERI: 'Eritrea',
  ESH: 'República Árabe Saharaui Democrática',
  ESP: 'España',
  EST: 'Estonia',
  ETH: 'Etiopía',
  FIN: 'Finlandia',
  FJI: 'Fiyi',
  FLK: 'Islas Malvinas',
  FRA: 'Francia',
  FRO: 'Islas Feroe',
  FSM: 'Micronesia',
  GAB: 'Gabón',
  GBR: 'Reino Unido',
  GEO: 'Georgia',
  GGY: 'Guernsey',
  GHA: 'Ghana',
  GIB: 'Gibraltar',
  GIN: 'Guinea',
  GLP: 'Guadalupe',
  GMB: 'Gambia',
  GNB: 'Guinea-Bisáu',
  GNQ: 'Guinea Ecuatorial',
  GRC: 'Grecia',
  GRD: 'Granada',
  GRL: 'Groenlandia',
  GTM: 'Guatemala',
  GUF: 'Guayana Francesa',
  GUM: 'Guam',
  GUY: 'Guyana',
  HKG: 'Hong Kong',
  HMD: 'Islas Heard y McDonald',
  HND: 'Honduras',
  HRV: 'Croacia',
  HTI: 'Haití',
  HUN: 'Hungría',
  IDN: 'Indonesia',
  IMN: 'Isla de Man',
  IND: 'India',
  IOT: 'Territorio Británico del Océano Índico',
  IRL: 'Irlanda',
  IRN: 'Irán',
  IRQ: 'Irak',
  ISL: 'Islandia',
  ISR: 'Israel',
  ITA: 'Italia',
  JAM: 'Jamaica',
  JEY: 'Jersey',
  JOR: 'Jordania',
  JPN: 'Japón',
  KAZ: 'Kazajistán',
  KEN: 'Kenia',
  KGZ: 'Kirguistán',
  KHM: 'Camboya',
  KIR: 'Kiribati',
  KNA: 'San Cristóbal y Nieves',
  KOR: 'Corea del Sur',
  KWT: 'Kuwait',
  LAO: 'Laos',
  LBN: 'Líbano',
  LBR: 'Liberia',
  LBY: 'Libia',
  LCA: 'Santa Lucía',
  LIE: 'Liechtenstein',
  LKA: 'Sri Lanka',
  LSO: 'Lesoto',
  LTU: 'Lituania',
  LUX: 'Luxemburgo',
  LVA: 'Letonia',
  MAC: 'Macao',
  MAF: 'San Martín',
  MAR: 'Marruecos',
  MCO: 'Mónaco',
  MDA: 'Moldavia',
  MDG: 'Madagascar',
  MDV: 'Maldivas',
  MEX: 'México',
  MHL: 'Islas Marshall',
  MKD: 'Macedonia del Norte',
  MLI: 'Mali',
  MLT: 'Malta',
  MMR: 'Birmania',
  MNE: 'Montenegro',
  MNG: 'Mongolia',
  MNP: 'Islas Marianas del Norte',
  MOZ: 'Mozambique',
  MRT: 'Mauritania',
  MSR: 'Montserrat',
  MTQ: 'Martinica',
  MUS: 'Mauricio',
  MWI: 'Malaui',
  MYS: 'Malasia',
  MYT: 'Mayotte',
  NAM: 'Namibia',
  NCL: 'Nueva Caledonia',
  NER: 'Níger',
  NFK: 'Isla Norfolk',
  NGA: 'Nigeria',
  NIC: 'Nicaragua',
  NIU: 'Niue',
  NLD: 'Países Bajos',
  NOR: 'Noruega',
  NPL: 'Nepal',
  NRU: 'Nauru',
  NZL: 'Nueva Zelanda',
  OMN: 'Omán',
  PAK: 'Pakistán',
  PAN: 'Panamá',
  PCN: 'Islas Pitcairn',
  PER: 'Perú',
  PHL: 'Filipinas',
  PLW: 'Palaos',
  PNG: 'Papúa Nueva Guinea',
  POL: 'Polonia',
  PRI: 'Puerto Rico',
  PRK: 'Corea del Norte',
  PRT: 'Portugal',
  PRY: 'Paraguay',
  PSE: 'Palestina',
  PYF: 'Polinesia Francesa',
  QAT: 'Catar',
  REU: 'Reunión',
  ROU: 'Rumania',
  RUS: 'Rusia',
  RWA: 'Ruanda',
  SAU: 'Arabia Saudita',
  SDN: 'Sudán',
  SEN: 'Senegal',
  SGP: 'Singapur',
  SGS: 'Islas Georgias del Sur y Sandwich del Sur',
  SHN: 'Santa Elena, Ascensión y Tristán de Acuña',
  SJM: 'Svalbard y Jan Mayen',
  SLB: 'Islas Salomón',
  SLE: 'Sierra Leona',
  SLV: 'El Salvador',
  SMR: 'San Marino',
  SOM: 'Somalia',
  SPM: 'San Pedro y Miquelón',
  SRB: 'Serbia',
  SSD: 'Sudán del Sur',
  STP: 'Santo Tomé y Príncipe',
  SUR: 'Surinam',
  SVK: 'Eslovaquia',
  SVN: 'Eslovenia',
  SWE: 'Suecia',
  SWZ: 'Suazilandia',
  SXM: 'San Martín',
  SYC: 'Seychelles',
  SYR: 'Siria',
  TCA: 'Islas Turcas y Caicos',
  TCD: 'Chad',
  TGO: 'Togo',
  THA: 'Tailandia',
  TJK: 'Tayikistán',
  TKL: 'Tokelau',
  TKM: 'Turkmenistán',
  TLS: 'Timor Oriental',
  TON: 'Tonga',
  TTO: 'Trinidad y Tobago',
  TUN: 'Túnez',
  TUR: 'Turquía',
  TUV: 'Tuvalu',
  TWN: 'Taiwán (República de China)',
  TZA: 'Tanzania',
  UGA: 'Uganda',
  UKR: 'Ucrania',
  UMI: 'Islas Ultramarinas Menores de los Estados Unidos',
  URY: 'Uruguay',
  USA: 'Estados Unidos',
  UZB: 'Uzbekistán',
  VAT: 'Vaticano, Ciudad del',
  VCT: 'San Vicente y las Granadinas',
  VEN: 'Venezuela',
  VGB: 'Islas Vírgenes Británicas',
  VIR: 'Islas Vírgenes de los Estados Unidos',
  VNM: 'Vietnam',
  VUT: 'Vanuatu',
  WLF: 'Wallis y Futuna',
  WSM: 'Samoa',
  YEM: 'Yemen',
  ZAF: 'Sudáfrica',
  ZMB: 'Zambia',
  ZWE: 'Zimbabue',
} as const satisfies Record<COUNTRY_CODES, string>;

export default ES;
