import type { COUNTRY_CODES } from '../codes';

const PT = {
  ABW: 'Aruba',
  AFG: 'Afeganistão',
  AGO: 'Angola',
  AIA: 'Anguila',
  ALA: 'Ilhas Åland',
  ALB: 'Albânia',
  AND: 'Andorra',
  ARE: 'Emirados Árabes Unidos',
  ARG: 'Argentina',
  ARM: 'Armênia',
  ASM: 'Samoa Americana',
  ATA: 'Antártida',
  ATF: 'Terras Austrais e Antárticas Francesas',
  ATG: 'Antígua e Barbuda',
  AUS: 'Austrália',
  AUT: 'Áustria',
  AZE: 'Azerbaijão',
  BDI: 'Burundi',
  BEL: 'Bélgica',
  BEN: 'Benim',
  BES: 'Países Baixos Caribenhos',
  BFA: 'Burquina Fasso',
  BGD: 'Bangladexe',
  BGR: 'Bulgária',
  BHR: 'Barém',
  BHS: 'Bahamas',
  BIH: 'Bósnia e Herzegovina',
  BLM: 'São Bartolomeu',
  BLR: 'Bielorrússia',
  BLZ: 'Belize',
  BMU: 'Bermudas',
  BOL: 'Bolívia',
  BRA: 'Brasil',
  BRB: 'Barbados',
  BRN: 'Brunei',
  BTN: 'Butão',
  BVT: 'Ilha Bouvet',
  BWA: 'Botsuana',
  CAF: 'República Centro-Africana',
  CAN: 'Canadá',
  CCK: 'Ilhas Cocos (Keeling)',
  CHE: 'Suíça',
  CHL: 'Chile',
  CHN: 'China',
  CIV: 'Costa do Marfim',
  CMR: 'Camarões',
  COD: 'República Democrática do Congo',
  COG: 'República do Congo',
  COK: 'Ilhas Cook',
  COL: 'Colômbia',
  COM: 'Comores',
  CPV: 'Cabo Verde',
  CRI: 'Costa Rica',
  CUB: 'Cuba',
  CUW: 'Curaçau',
  CXR: 'Ilha do Natal',
  CYM: 'Ilhas Caimã',
  CYP: 'Chipre',
  CZE: 'Chéquia',
  DEU: 'Alemanha',
  DJI: 'Djibuti',
  DMA: 'Dominica',
  DNK: 'Dinamarca',
  DOM: 'República Dominicana',
  DZA: 'Argélia',
  ECU: 'Equador',
  EGY: 'Egito',
  ERI: 'Eritreia',
  ESH: 'Saara Ocidental',
  ESP: 'Espanha',
  EST: 'Estónia',
  ETH: 'Etiópia',
  FIN: 'Finlândia',
  FJI: 'Fiji',
  FLK: 'Ilhas Malvinas',
  FRA: 'França',
  FRO: 'Ilhas Feroé',
  FSM: 'Estados Federados da Micronésia',
  GAB: 'Gabão',
  GBR: 'Reino Unido',
  GEO: 'Geórgia',
  GGY: 'Guernsey',
  GHA: 'Gana',
  GIB: 'Gibraltar',
  GIN: 'Guiné',
  GLP: 'Guadalupe',
  GMB: 'Gâmbia',
  GNB: 'Guiné-Bissau',
  GNQ: 'Guiné Equatorial',
  GRC: 'Grécia',
  GRD: 'Granada',
  GRL: 'Gronelândia',
  GTM: 'Guatemala',
  GUF: 'Guiana Francesa',
  GUM: 'Guam',
  GUY: 'Guiana',
  HKG: 'Hong Kong',
  HMD: 'Ilha Heard e Ilhas McDonald',
  HND: 'Honduras',
  HRV: 'Croácia',
  HTI: 'Haiti',
  HUN: 'Hungria',
  IDN: 'Indonésia',
  IMN: 'Ilha de Man',
  IND: 'Índia',
  IOT: 'Território Britânico do Oceano Índico',
  IRL: 'Irlanda',
  IRN: 'Irã',
  IRQ: 'Iraque',
  ISL: 'Islândia',
  ISR: 'Israel',
  ITA: 'Itália',
  JAM: 'Jamaica',
  JEY: 'Jersey',
  JOR: 'Jordânia',
  JPN: 'Japão',
  KAZ: 'Cazaquistão',
  KEN: 'Quênia',
  KGZ: 'Quirguistão',
  KHM: 'Camboja',
  KIR: 'Quiribáti',
  KNA: 'São Cristóvão e Neves',
  KOR: 'Coreia do Sul',
  KWT: 'Kuwait',
  LAO: 'Laos',
  LBN: 'Líbano',
  LBR: 'Libéria',
  LBY: 'Líbia',
  LCA: 'Santa Lúcia',
  LIE: 'Listenstaine',
  LKA: 'Seri Lanca',
  LSO: 'Lesoto',
  LTU: 'Lituânia',
  LUX: 'Luxemburgo',
  LVA: 'Letónia',
  MAC: 'Macau',
  MAF: 'São Martinho',
  MAR: 'Marrocos',
  MCO: 'Mónaco',
  MDA: 'Moldávia',
  MDG: 'Madagáscar',
  MDV: 'Maldivas',
  MEX: 'México',
  MHL: 'Ilhas Marshall',
  MKD: 'Macedônia do Norte',
  MLI: 'Mali',
  MLT: 'Malta',
  MMR: 'Mianmar',
  MNE: 'Montenegro',
  MNG: 'Mongólia',
  MNP: 'Marianas Setentrionais',
  MOZ: 'Moçambique',
  MRT: 'Mauritânia',
  MSR: 'Monserrate',
  MTQ: 'Martinica',
  MUS: 'Ilhas Maurícias',
  MWI: 'Maláui',
  MYS: 'Malásia',
  MYT: 'Maiote',
  NAM: 'Namíbia',
  NCL: 'Nova Caledônia',
  NER: 'Níger',
  NFK: 'Ilha Norfolk',
  NGA: 'Nigéria',
  NIC: 'Nicarágua',
  NIU: 'Niue',
  NLD: 'Países Baixos',
  NOR: 'Noruega',
  NPL: 'Nepal',
  NRU: 'Nauru',
  NZL: 'Nova Zelândia',
  OMN: 'Omã',
  PAK: 'Paquistão',
  PAN: 'Panamá',
  PCN: 'Pitcairn',
  PER: 'Peru',
  PHL: 'Filipinas',
  PLW: 'Palau',
  PNG: 'Papua-Nova Guiné',
  POL: 'Polónia',
  PRI: 'Porto Rico',
  PRK: 'Coreia do Norte',
  PRT: 'Portugal',
  PRY: 'Paraguai',
  PSE: 'Palestina',
  PYF: 'Polinésia Francesa',
  QAT: 'Catar',
  REU: 'Reunião',
  ROU: 'Roménia',
  RUS: 'Rússia',
  RWA: 'Ruanda',
  SAU: 'Arábia Saudita',
  SDN: 'Sudão',
  SEN: 'Senegal',
  SGP: 'Singapura',
  SGS: 'Ilhas Geórgia do Sul e Sandwich do Sul',
  SHN: 'Santa Helena, Ascensão e Tristão da Cunha',
  SJM: 'Esvalbarde e Jan Mayen',
  SLB: 'Ilhas Salomão',
  SLE: 'Serra Leoa',
  SLV: 'El Salvador',
  SMR: 'San Marino',
  SOM: 'Somália',
  SPM: 'São Pedro e Miquelão',
  SRB: 'Sérvia',
  SSD: 'Sudão do Sul',
  STP: 'São Tomé e Príncipe',
  SUR: 'Suriname',
  SVK: 'Eslováquia',
  SVN: 'Eslovênia',
  SWE: 'Suécia',
  SWZ: 'Essuatíni',
  SXM: 'São Martinho',
  SYC: 'Seicheles',
  SYR: 'Síria',
  TCA: 'Turcas e Caicos',
  TCD: 'Chade',
  TGO: 'Togo',
  THA: 'Tailândia',
  TJK: 'Tajiquistão',
  TKL: 'Toquelau',
  TKM: 'Turcomenistão',
  TLS: 'Timor-Leste',
  TON: 'Tonga',
  TTO: 'Trinidad e Tobago',
  TUN: 'Tunísia',
  TUR: 'Turquia',
  TUV: 'Tuvalu',
  TWN: 'Taiwan',
  TZA: 'Tanzânia',
  UGA: 'Uganda',
  UKR: 'Ucrânia',
  UMI: 'Ilhas Menores Distantes dos Estados Unidos',
  URY: 'Uruguai',
  USA: 'Estados Unidos',
  UZB: 'Uzbequistão',
  VAT: 'Vaticano',
  VCT: 'São Vicente e Granadinas',
  VEN: 'Venezuela',
  VGB: 'Ilhas Virgens Britânicas',
  VIR: 'Ilhas Virgens Americanas',
  VNM: 'Vietname',
  VUT: 'Vanuatu',
  WLF: 'Wallis e Futuna',
  WSM: 'Samoa',
  YEM: 'Iêmen',
  ZAF: 'África do Sul',
  ZMB: 'Zâmbia',
  ZWE: 'Zimbábue',
} as const satisfies Record<COUNTRY_CODES, string>;

export default PT;
