/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteRouteImport } from './routes/demo/route'
import { Route as IndexRouteRouteImport } from './routes/index/route'
import { Route as IntermediariesCreateRouteRouteImport } from './routes/intermediaries/create/route'
import { Route as AuthRegisterRouteRouteImport } from './routes/auth/register/route'
import { Route as AuthLoginRouteRouteImport } from './routes/auth/login/route'
import { Route as AssetsCreateRouteRouteImport } from './routes/assets/create/route'
import { Route as IntermediariesIndexRouteRouteImport } from './routes/intermediaries/index/route'
import { Route as AssetsIndexRouteRouteImport } from './routes/assets/index/route'
import { Route as IntermediariesEditIdRouteRouteImport } from './routes/intermediaries/edit/$id/route'
import { Route as AssetsEditIdRouteRouteImport } from './routes/assets/edit/$id/route'

const DemoRouteRoute = DemoRouteRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntermediariesCreateRouteRoute =
  IntermediariesCreateRouteRouteImport.update({
    id: '/intermediaries/create',
    path: '/intermediaries/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthRegisterRouteRoute = AuthRegisterRouteRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRouteRoute = AuthLoginRouteRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsCreateRouteRoute = AssetsCreateRouteRouteImport.update({
  id: '/assets/create',
  path: '/assets/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IntermediariesIndexRouteRoute =
  IntermediariesIndexRouteRouteImport.update({
    id: '/intermediaries/',
    path: '/intermediaries/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssetsIndexRouteRoute = AssetsIndexRouteRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntermediariesEditIdRouteRoute =
  IntermediariesEditIdRouteRouteImport.update({
    id: '/intermediaries/edit/$id',
    path: '/intermediaries/edit/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssetsEditIdRouteRoute = AssetsEditIdRouteRouteImport.update({
  id: '/assets/edit/$id',
  path: '/assets/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/demo': typeof DemoRouteRoute
  '/assets': typeof AssetsIndexRouteRoute
  '/intermediaries': typeof IntermediariesIndexRouteRoute
  '/assets/create': typeof AssetsCreateRouteRoute
  '/auth/login': typeof AuthLoginRouteRoute
  '/auth/register': typeof AuthRegisterRouteRoute
  '/intermediaries/create': typeof IntermediariesCreateRouteRoute
  '/assets/edit/$id': typeof AssetsEditIdRouteRoute
  '/intermediaries/edit/$id': typeof IntermediariesEditIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/demo': typeof DemoRouteRoute
  '/assets': typeof AssetsIndexRouteRoute
  '/intermediaries': typeof IntermediariesIndexRouteRoute
  '/assets/create': typeof AssetsCreateRouteRoute
  '/auth/login': typeof AuthLoginRouteRoute
  '/auth/register': typeof AuthRegisterRouteRoute
  '/intermediaries/create': typeof IntermediariesCreateRouteRoute
  '/assets/edit/$id': typeof AssetsEditIdRouteRoute
  '/intermediaries/edit/$id': typeof IntermediariesEditIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/demo': typeof DemoRouteRoute
  '/assets/': typeof AssetsIndexRouteRoute
  '/intermediaries/': typeof IntermediariesIndexRouteRoute
  '/assets/create': typeof AssetsCreateRouteRoute
  '/auth/login': typeof AuthLoginRouteRoute
  '/auth/register': typeof AuthRegisterRouteRoute
  '/intermediaries/create': typeof IntermediariesCreateRouteRoute
  '/assets/edit/$id': typeof AssetsEditIdRouteRoute
  '/intermediaries/edit/$id': typeof IntermediariesEditIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/assets'
    | '/intermediaries'
    | '/assets/create'
    | '/auth/login'
    | '/auth/register'
    | '/intermediaries/create'
    | '/assets/edit/$id'
    | '/intermediaries/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/assets'
    | '/intermediaries'
    | '/assets/create'
    | '/auth/login'
    | '/auth/register'
    | '/intermediaries/create'
    | '/assets/edit/$id'
    | '/intermediaries/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/assets/'
    | '/intermediaries/'
    | '/assets/create'
    | '/auth/login'
    | '/auth/register'
    | '/intermediaries/create'
    | '/assets/edit/$id'
    | '/intermediaries/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  DemoRouteRoute: typeof DemoRouteRoute
  AssetsIndexRouteRoute: typeof AssetsIndexRouteRoute
  IntermediariesIndexRouteRoute: typeof IntermediariesIndexRouteRoute
  AssetsCreateRouteRoute: typeof AssetsCreateRouteRoute
  AuthLoginRouteRoute: typeof AuthLoginRouteRoute
  AuthRegisterRouteRoute: typeof AuthRegisterRouteRoute
  IntermediariesCreateRouteRoute: typeof IntermediariesCreateRouteRoute
  AssetsEditIdRouteRoute: typeof AssetsEditIdRouteRoute
  IntermediariesEditIdRouteRoute: typeof IntermediariesEditIdRouteRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intermediaries/create': {
      id: '/intermediaries/create'
      path: '/intermediaries/create'
      fullPath: '/intermediaries/create'
      preLoaderRoute: typeof IntermediariesCreateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/create': {
      id: '/assets/create'
      path: '/assets/create'
      fullPath: '/assets/create'
      preLoaderRoute: typeof AssetsCreateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intermediaries/': {
      id: '/intermediaries/'
      path: '/intermediaries'
      fullPath: '/intermediaries'
      preLoaderRoute: typeof IntermediariesIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intermediaries/edit/$id': {
      id: '/intermediaries/edit/$id'
      path: '/intermediaries/edit/$id'
      fullPath: '/intermediaries/edit/$id'
      preLoaderRoute: typeof IntermediariesEditIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/edit/$id': {
      id: '/assets/edit/$id'
      path: '/assets/edit/$id'
      fullPath: '/assets/edit/$id'
      preLoaderRoute: typeof AssetsEditIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  DemoRouteRoute: DemoRouteRoute,
  AssetsIndexRouteRoute: AssetsIndexRouteRoute,
  IntermediariesIndexRouteRoute: IntermediariesIndexRouteRoute,
  AssetsCreateRouteRoute: AssetsCreateRouteRoute,
  AuthLoginRouteRoute: AuthLoginRouteRoute,
  AuthRegisterRouteRoute: AuthRegisterRouteRoute,
  IntermediariesCreateRouteRoute: IntermediariesCreateRouteRoute,
  AssetsEditIdRouteRoute: AssetsEditIdRouteRoute,
  IntermediariesEditIdRouteRoute: IntermediariesEditIdRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
