/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteRouteImport } from './routes/index/route'
import { Route as IntermediariesCreateRouteRouteImport } from './routes/intermediaries/create/route'
import { Route as ContractsCreateRouteRouteImport } from './routes/contracts/create/route'
import { Route as AuthRegisterRouteRouteImport } from './routes/auth/register/route'
import { Route as AuthLoginRouteRouteImport } from './routes/auth/login/route'
import { Route as IntermediariesIndexRouteRouteImport } from './routes/intermediaries/index/route'
import { Route as ContractsIndexRouteRouteImport } from './routes/contracts/index/route'
import { Route as IntermediariesEditIdRouteRouteImport } from './routes/intermediaries/edit/$id/route'
import { Route as ContractsEditIdRouteRouteImport } from './routes/contracts/edit/$id/route'

const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntermediariesCreateRouteRoute =
  IntermediariesCreateRouteRouteImport.update({
    id: '/intermediaries/create',
    path: '/intermediaries/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContractsCreateRouteRoute = ContractsCreateRouteRouteImport.update({
  id: '/contracts/create',
  path: '/contracts/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRouteRoute = AuthRegisterRouteRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRouteRoute = AuthLoginRouteRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntermediariesIndexRouteRoute =
  IntermediariesIndexRouteRouteImport.update({
    id: '/intermediaries/',
    path: '/intermediaries/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContractsIndexRouteRoute = ContractsIndexRouteRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntermediariesEditIdRouteRoute =
  IntermediariesEditIdRouteRouteImport.update({
    id: '/intermediaries/edit/$id',
    path: '/intermediaries/edit/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContractsEditIdRouteRoute = ContractsEditIdRouteRouteImport.update({
  id: '/contracts/edit/$id',
  path: '/contracts/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/contracts': typeof ContractsIndexRouteRoute
  '/intermediaries': typeof IntermediariesIndexRouteRoute
  '/auth/login': typeof AuthLoginRouteRoute
  '/auth/register': typeof AuthRegisterRouteRoute
  '/contracts/create': typeof ContractsCreateRouteRoute
  '/intermediaries/create': typeof IntermediariesCreateRouteRoute
  '/contracts/edit/$id': typeof ContractsEditIdRouteRoute
  '/intermediaries/edit/$id': typeof IntermediariesEditIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/contracts': typeof ContractsIndexRouteRoute
  '/intermediaries': typeof IntermediariesIndexRouteRoute
  '/auth/login': typeof AuthLoginRouteRoute
  '/auth/register': typeof AuthRegisterRouteRoute
  '/contracts/create': typeof ContractsCreateRouteRoute
  '/intermediaries/create': typeof IntermediariesCreateRouteRoute
  '/contracts/edit/$id': typeof ContractsEditIdRouteRoute
  '/intermediaries/edit/$id': typeof IntermediariesEditIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/contracts/': typeof ContractsIndexRouteRoute
  '/intermediaries/': typeof IntermediariesIndexRouteRoute
  '/auth/login': typeof AuthLoginRouteRoute
  '/auth/register': typeof AuthRegisterRouteRoute
  '/contracts/create': typeof ContractsCreateRouteRoute
  '/intermediaries/create': typeof IntermediariesCreateRouteRoute
  '/contracts/edit/$id': typeof ContractsEditIdRouteRoute
  '/intermediaries/edit/$id': typeof IntermediariesEditIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contracts'
    | '/intermediaries'
    | '/auth/login'
    | '/auth/register'
    | '/contracts/create'
    | '/intermediaries/create'
    | '/contracts/edit/$id'
    | '/intermediaries/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contracts'
    | '/intermediaries'
    | '/auth/login'
    | '/auth/register'
    | '/contracts/create'
    | '/intermediaries/create'
    | '/contracts/edit/$id'
    | '/intermediaries/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/contracts/'
    | '/intermediaries/'
    | '/auth/login'
    | '/auth/register'
    | '/contracts/create'
    | '/intermediaries/create'
    | '/contracts/edit/$id'
    | '/intermediaries/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  ContractsIndexRouteRoute: typeof ContractsIndexRouteRoute
  IntermediariesIndexRouteRoute: typeof IntermediariesIndexRouteRoute
  AuthLoginRouteRoute: typeof AuthLoginRouteRoute
  AuthRegisterRouteRoute: typeof AuthRegisterRouteRoute
  ContractsCreateRouteRoute: typeof ContractsCreateRouteRoute
  IntermediariesCreateRouteRoute: typeof IntermediariesCreateRouteRoute
  ContractsEditIdRouteRoute: typeof ContractsEditIdRouteRoute
  IntermediariesEditIdRouteRoute: typeof IntermediariesEditIdRouteRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intermediaries/create': {
      id: '/intermediaries/create'
      path: '/intermediaries/create'
      fullPath: '/intermediaries/create'
      preLoaderRoute: typeof IntermediariesCreateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/create': {
      id: '/contracts/create'
      path: '/contracts/create'
      fullPath: '/contracts/create'
      preLoaderRoute: typeof ContractsCreateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intermediaries/': {
      id: '/intermediaries/'
      path: '/intermediaries'
      fullPath: '/intermediaries'
      preLoaderRoute: typeof IntermediariesIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/': {
      id: '/contracts/'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intermediaries/edit/$id': {
      id: '/intermediaries/edit/$id'
      path: '/intermediaries/edit/$id'
      fullPath: '/intermediaries/edit/$id'
      preLoaderRoute: typeof IntermediariesEditIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/edit/$id': {
      id: '/contracts/edit/$id'
      path: '/contracts/edit/$id'
      fullPath: '/contracts/edit/$id'
      preLoaderRoute: typeof ContractsEditIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  ContractsIndexRouteRoute: ContractsIndexRouteRoute,
  IntermediariesIndexRouteRoute: IntermediariesIndexRouteRoute,
  AuthLoginRouteRoute: AuthLoginRouteRoute,
  AuthRegisterRouteRoute: AuthRegisterRouteRoute,
  ContractsCreateRouteRoute: ContractsCreateRouteRoute,
  IntermediariesCreateRouteRoute: IntermediariesCreateRouteRoute,
  ContractsEditIdRouteRoute: ContractsEditIdRouteRoute,
  IntermediariesEditIdRouteRoute: IntermediariesEditIdRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
